pythonindia/wye

requirements/dev.txt
Hey @vnbang2003, I want to contribute to this project. Can you provide more details in the README file ?
=> Bug Fix: requirements file updated

requirements/base.txt
=> requirements: base.txt updated for djangorestframework and django-filter

wye/base/constants.py, wye/base/emailer.py, wye/workshops/admin.py, wye/workshops/decorators.py, wye/workshops/forms.py, wye/workshops/models.py, wye/workshops/urls.py, wye/workshops/views.py
Addresses: https://github.com/pythonindia/wye/issues/8 
Allows presenter to self assign workshop 
Restriction: Presenter cannot assign to self, if workshop is completed.
Urls:
http://127.0.0.1:8000/workshop/presenter/opt-in/1/
http://127.0.0.1:8000/workshop/presenter/opt-out/1/
=> Wye 8 (Workshop selection page)

wye/base/management/commands/sample_data.py
=> Generate sample data

wye/templates/base.html
=> links bootstrap.min.js

wye/base/views.py, wye/templates/index.html
Completes #59
I have assumed that the slug of Tutor user is tutor which @ultimatecoder said in #58 that he will add in sample_data.py in upcoming PR
=> Add query to show stats on home page

wye/organisations/admin.py, wye/profiles/admin.py, wye/regions/admin.py, wye/workshops/admin.py
Fixed #45.
screenshots from the panel of workshop model. Others are similar but the change model pages are different for others.
=> creates AdminModel classes for each model.

CONTRIBUTORS.txt, README.md, wye/base/management/commands/sample_data.py
- Fix https://github.com/pythonindia/wye/issues/79
=> Fix admin email

README.md
correct the spelling of experienced.
=> spelling mistake in readme 

wye/templates/about.html, wye/templates/index.html
Please review the content once.
=> Content edits

wye/templates/about.html, wye/templates/account/login.html, wye/templates/account/password_reset.html, wye/templates/account/password_reset_done.html, wye/templates/account/signup.html, wye/templates/account/verification_sent.html, wye/templates/base.html, wye/templates/organisation/create.html, wye/templates/organisation/detail.html, wye/templates/organisation/edit.html, wye/templates/organisation/list.html, wye/templates/profile/details.html, wye/templates/profile/index.html, wye/templates/regions/index.html, wye/templates/regions/lead/create.html, wye/templates/regions/lead/edit.html, wye/templates/regions/location/create.html, wye/templates/regions/location/edit.html, wye/templates/regions/state/create.html, wye/templates/regions/state/edit.html, wye/templates/workshops/workshop_create.html, wye/templates/workshops/workshop_detail.html, wye/templates/workshops/workshop_list.html, wye/templates/workshops/workshop_update.html
=> adds breadcrumbs in navigation

wye/profiles/views.py, wye/templates/profile/dashboard.html
This does not contains the button to submit feedback for the workshop.
=> adds html code for dashboard with user type as TUTOR

wye/base/widgets.py, wye/workshops/mixins.py, wye/workshops/views.py
Also, added database query for workshop_completed list.
=> Added Workshop access mixin and fixed workshop update form bug

settings/common.py, wye/profiles/models.py, wye/profiles/views.py
This PR fixes the broken `slug` field error in case of broken dashboard.
=> slug field fix for create profile

wye/profiles/views.py, wye/templates/profile/admin_dashboard.html, wye/templates/profile/college_poc_dashboard.html, wye/templates/profile/dashboard.html, wye/templates/profile/regional_lead_dashboard.html, wye/templates/profile/tutor_dashboard.html, wye/templates/workshops/workshop_display.html, wye/workshops/templatetags/workshop_display.py
This PR is of specific commits from PR #108 . It includes
* custom template tag for workshop display under workshop app
* dashboard.html is changed to include pages for each user type
* includes individual dashboard pages for admin, college poc, regional lead and tutor.
* includes some views code and sets variables in the context
=> New dashboard user : from PR 108

wye/templates/workshops/workshop_list.html, wye/workshops/mixins.py, wye/workshops/views.py
Contains 2nd part implementation for #9 
- Restricting organisation to add workshop unless they complete feedback
- Restricting presenter to take up next workshop unless they complete feedback
Also contains fix for #102
=> Wye 9 workshop restriction

wye/profiles/migrations/0004_auto_20151101_1553.py, wye/profiles/models.py, wye/templates/profile/index.html
* **Description**: It might be possible that User don't want to display their contact details such as Email address or Mobile number to their Public profile. For that reason, adding functionality to allow user to hide / show their Email address or Mobile number.
* **Default**: The Email Address and Mobile number is by default visible to the profile.
* **Steps to Hide Email Address or Mobile Number:** 
1 Click **Edit** button available at their profile.
2 There will be two Check box fields "Is Email Visible" and "Is Mobile Visible" respectively which allows them to set appropriate visibility option.
* **[Video](https://youtu.be/xmfWvQqVUKM)**
* **Issues**:
1 #129
=> Option to hide Email Address or Mobile number from User public profile page

wye/templates/email_messages/layout.html
Adds mailer template base layout #99
It follows MailChimp's email template.
**Reference:** https://github.com/mailchimp/email-blueprints/blob/master/responsive-templates/base_boxed_basic_2column_query.html
Todo:
- We have to set up config for unsubscribe, update subscription preferences, etc. As of now it follows mailchimp's templates *|UNSUB|*, *|UPDATE_PROFILE|*, etc. (and there are more fields at footer).
- Update all images, including logo, with absolute url.
=> Mailer template

settings/__init__.py
settings init did not have support for prod, adding that.
=> import from prod also

wye/base/constants.py, wye/profiles/forms.py, wye/profiles/views.py, wye/templates/base.html, wye/templates/contact.html, wye/templates/email_messages/contactus/message.html, wye/templates/email_messages/contactus/message.txt, wye/templates/email_messages/contactus/message_user.html, wye/templates/email_messages/contactus/message_user.txt, wye/urls.py
This PR adds the functionality of contact page. The url is `/contact` and right now any tab is not made for the same.
=> contact us page : basic commit, url is /contact

wye/templates/email_messages/contactus/message.html, wye/templates/email_messages/contactus/message_user.html
This PR changes the email html for contact us page. The message and subject may still need modifications
=> proper email html for the contact us page

settings/common.py, wye/templates/index.html
- A space was missing on the index page
- Mailing list URL corrected
=> Fixes small typo and broken link

wye/workshops/forms.py
=> workshop expected date only after 2 weeks

wye/profiles/urls.py
This PR adds support for using email as username in the urls.
=> adds support for email as username

wye/workshops/models.py
=> limits maximum no of participants for a workshop

tests/functional/test_edit_profile.py, tests/functional/test_user_flow.py, tests/unit/required_asterisk.py, wye/profiles/forms.py, wye/profiles/models.py
=> Mandatory fields shown as asterisk while updating profile

tests/functional/workshop/base.py, tests/functional/workshop/test_workshop_list.py, wye/workshops/views.py
Addresses #220  issue.
I have fix the query for regional lead in WorkshopList view.
=> fix query for regional lead in workshoplist view

wye/base/management/commands/sample_data.py
Fix for #245 . Please let me know if any other changes are required.
Thanks
=> Auto verify admin beier on creation

tests/factories.py, tests/functional/test_regional_lead_flow.py, wye/regions/forms.py
fixed #171.
I have updated the tests accordingly but the script test's behavior is slightly different from what i tested manually. @vnbang2003 please see if the test I have written looks fine to you or else suggest whatever changes are required.
=>  Regional Lead usertype update

wye/base/management/commands/sample_data.py, wye/profiles/views.py, wye/urls.py
This PR converts Contact Us class based view to a function based view as per issue #256
=> Profiles: Convert Contact Us CBV to FBV

requirements/dev.txt, settings/common.py, wye/workshops/tasks.py
=> Remainder to Presenter/Requester a week before workshop

wye/templates/faq.html
=> chore(faq): updated faq section

wye/workshops/views.py
Signed-off-by: Haris Ibrahim K. V <blucalvin@gmail.com>
=> Fixes #282. Uses the 'Sites' module to fetch the current domain

wye/workshops/models.py
=> Fixes issue: #283, New workshop request emails

requirements/base.txt, requirements/dev.txt
Add celery. This helps in adding background tasks.
=> Move celery requirements to base

wye/templates/faq.html
@vnbang2003 merge if you thing it looks good.
=> Update styling of FAQ page

settings/common.py, wye/base/context_processors.py, wye/organisations/migrations/0003_auto_20160815_0955.py, wye/organisations/models.py, wye/templates/organisation/create.html, wye/templates/organisation/detail.html
Address issue #300 
Added new field to capture full address, pincode and address map url. 
Note: 
- In organisation details page map will be displayed if full address is provided.
- Before deploying the changes in production, generate google map api key (enable it for Google Maps Embed API  and Google Maps JavaScript API )  and set GOOGLE_MAP_API key in environment.
=> Wye #300 Add address fields for organisation

wye/workshops/models.py
=> Issue fix 283

wye/templates/workshops/workshop_detail.html, wye/workshops/forms.py
=> Add action buttons on Workshop detail page

wye/templates/workshops/workshop_detail.html
Minor Fix:
`%s/praticipants/participants/g`
=> [MINOR] Fix incorrect spelling

settings/common.py
I didn't realise that many file changes. #367 :)
Thanks
@vnbang2003
=> added facebook link in footer

wye/templates/workshops/workshop_list.html
=> Make rows clickable for all on workshop list page

README.md, tests/factories.py, tests/functional/test_edit_profile.py, tests/functional/test_workshops_flow.py, wye/organisations/views.py, wye/profiles/forms.py, wye/profiles/models.py, wye/templates/faq.html, wye/workshops/admin.py, wye/workshops/forms.py, wye/workshops/migrations/0009_workshopratingvalues_feedback_type.py, wye/workshops/models.py, wye/workshops/templatetags/workshop_action_button.py, wye/workshops/urls.py, wye/workshops/views.py
=> Merge development to master

tests/functional/test_reports.py, tests/functional/test_workshops_flow.py, tests/functional/workshop/test_workshop_list.py, wye/base/constants.py, wye/profiles/models.py, wye/profiles/views.py, wye/reports/urls.py, wye/reports/views.py, wye/templates/base.html, wye/templates/profile/index.html, wye/templates/reports/index.html, wye/templates/reports/workshop_details.html, wye/templates/workshops/workshop_detail.html, wye/templates/workshops/workshop_list.html, wye/workshops/forms.py, wye/workshops/models.py, wye/workshops/views.py
Add report, fixed workshop details page button issue
=> Add report, fixed workshop details page button issue

wye/profiles/views.py, wye/workshops/views.py
Added workshop is_active filter in profile
=> Added workshop is_active filter in profile

wye/profiles/views.py
Added is_active filter for profile workshop query
=> Added is_active filter for profile workshop query

wye/profiles/models.py
Added is_active filter in graph and count  section of profile
=> Added is_active filter in graph and count  section of profile

wye/workshops/templatetags/workshop_action_button.py
Fix the profile check validation
=> Fix the profile check validation

wye/templates/workshops/workshop_detail.html
Fixed Issue #337 .
Added feedback display for admin
=> Added feedback display for admin

wye/templates/index.html, wye/workshops/views.py
Added blog link "Request to support PythonExpress Project"
=> Added blog link "Request to support PythonExpress Project"

wye/templates/workshops/workshop_detail.html, wye/workshops/models.py
Fix for details page and email None
=> Fix for details page and email None

tests/functional/test_contact_page.py, wye/profiles/views.py
I have added code to auto fill the name and email field in the Contact Us page's form if the user is already logged in.
=> Autofilling name and email in Contact_us Form functionality added #209

requirements/base.txt, wye/reports/views.py
Upgrade django-allauth version and temp fix for report download
=> Upgrade django-allauth version and temp fix for report download

wye/base/constants.py, wye/templates/workshops/workshop_detail.html, wye/workshops/migrations/0014_workshop_target_audience.py, wye/workshops/models.py, wye/workshops/views.py
=> Added target Audience Fields

wye/profiles/migrations/0010_auto_20170907_0003.py, wye/profiles/models.py, wye/workshops/migrations/0015_auto_20170907_0003.py, wye/workshops/views.py
=> Pull for master with DB clean

wye/templates/workshops/workshop_detail.html
=> Fixed UI display
